# Generated by Django 5.0.4 on 2024-06-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='country',
            new_name='pays',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='city',
            new_name='ville',
        ),
    ]
