# Generated by Django 5.0.4 on 2024-06-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_country_contact_pays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='heure_d_ouverture',
            field=models.CharField(default=9, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='heure_de_fermeture',
            field=models.CharField(default=9, max_length=10),
            preserve_default=False,
        ),
    ]
