# Generated by Django 5.0.4 on 2024-06-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contact_heure_d_ouverture_contact_heure_de_fermeture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='jours_d_ouverture',
            field=models.CharField(default=5, max_length=30),
            preserve_default=False,
        ),
    ]
