# Generated by Django 5.0.4 on 2024-07-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_imagemodel_image_remove_contact_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='introduction',
            field=models.CharField(default=5, max_length=80),
            preserve_default=False,
        ),
    ]
