# Generated by Django 5.0.4 on 2024-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_lien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lien',
            name='lien',
            field=models.TextField(choices=[('fa-facebook-f', 'Facebook'), ('fa-youtube', 'Youtube'), ('fa-twitter', 'Twitter'), ('fa-linkedin-in', 'LinkedIn'), ('fa-instagram', 'Instagram'), ('fa-pinterest', 'Pinterest')]),
        ),
    ]
