# Generated by Django 5.0.4 on 2024-07-01 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_lien_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='lien',
            name='social_media',
            field=models.TextField(choices=[('fa-facebook-f', 'Facebook'), ('fa-youtube', 'Youtube'), ('fa-twitter', 'Twitter'), ('fa-linkedin-in', 'LinkedIn'), ('fa-instagram', 'Instagram'), ('fa-pinterest', 'Pinterest')], default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lien',
            name='lien',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lien',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.contact'),
        ),
    ]
