# Generated by Django 5.0.4 on 2024-07-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_lien_social_media_alter_lien_lien_alter_lien_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sujet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
