# Generated by Django 5.0.4 on 2024-07-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_message_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lien_google_map',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
    ]
