# Generated by Django 5.0.4 on 2024-07-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_contact_lien_google_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='lien_google_map',
            new_name='lien_google_maps',
        ),
    ]
